name: Daily README AutoUpdate

on:
  schedule:
    # 每天UTC时间0点运行（北京时间8点）
    - cron: "0 0 * * *"
  # 手动触发选项（可选）
  workflow_dispatch:
  # 当代码变更时也触发（可选）
  push:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # 必须开启写入权限
        persist-credentials: false
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        
    - name: Install dependencies
      run: |
        # 如果有requirements.txt则安装
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run auto_generate.py
      run: python3 auto_generate.py
      
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto Update README"
        git push origin HEAD:main
      env:
        # 需提前在仓库Settings → Secrets添加PAT
        GITHUB_TOKEN: ${{ secrets.PAT }}